### PR TITLE
auto-set-default-to-latest-expansion

### PR DESCRIPTION
**Pull request by Jaehyuk-Lee**
I think this is better to set default expansion.

### CODE REVIEW

**Comment by goaaats** [comment]
This already is the case, at least for me - can someone else confirm?

**Comment by blckshdw** [comment]
I had a default value as well

**Comment by Jaehyuk-Lee** [comment]
I mean, you don't have to change default value when another expansion releases.

**Comment by sslesar** [comment]
Some people have starter edition or trial.

**Comment by goaaats** [comment]
That should be fine since I clamp the maximum expansion level based on what square provides: https://github.com/goaaats/FFXIVQuickLauncher/blob/master/XIVLauncher/XIVGame.cs#L44

Really, I might as well get rid of that option, since all it does it change the title screen.

**Comment by Jaehyuk-Lee** [comment]
Ah, I didn't know that does only changes title screen. I think it's ok to remove it. I thought it was existing because some change happens in launcher with other expansions.

**Pull request closed without merging**
